/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aed.lab2;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author pavel
 */
public class Presentacion extends javax.swing.JPanel {

    /**
     * Creates new form Presentacion
     */
    public Presentacion() {
        initComponents();
        
        imagen(imgUNI);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPresentacion = new javax.swing.JPanel();
        imgUNI = new javax.swing.JLabel();
        txtAsignatura = new javax.swing.JLabel();
        txtDocente = new javax.swing.JLabel();
        txtCarrera = new javax.swing.JLabel();
        txtDocente2 = new javax.swing.JLabel();
        txtGrupo = new javax.swing.JLabel();
        txtGrupo2 = new javax.swing.JLabel();
        txtIntegrantes = new javax.swing.JLabel();
        txtIntegrantes2 = new javax.swing.JLabel();
        txtIntegrantes3 = new javax.swing.JLabel();
        txtAsignatura1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        panelPresentacion.setBackground(new java.awt.Color(255, 255, 255));

        txtAsignatura.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtAsignatura.setText("Algoritmos y Estructuras de Datos");

        txtDocente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtDocente.setText("Docente:");

        txtCarrera.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtCarrera.setText("Ingeniería en Computación");

        txtDocente2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtDocente2.setText("Eliezer Aburto.");

        txtGrupo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtGrupo.setText("Grupo:");

        txtGrupo2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtGrupo2.setText("2M5-CO.");

        txtIntegrantes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtIntegrantes.setText("Integrantes:");

        txtIntegrantes2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtIntegrantes2.setText("-Pável Josué García Rivas (2021-0108U).");

        txtIntegrantes3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtIntegrantes3.setText("-Yender Enrique Martinez López (2021-0262U).");

        txtAsignatura1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtAsignatura1.setText("Facultad de Electrotecnia y Computación");

        javax.swing.GroupLayout panelPresentacionLayout = new javax.swing.GroupLayout(panelPresentacion);
        panelPresentacion.setLayout(panelPresentacionLayout);
        panelPresentacionLayout.setHorizontalGroup(
            panelPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPresentacionLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(panelPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgUNI, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPresentacionLayout.createSequentialGroup()
                        .addComponent(txtDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDocente2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPresentacionLayout.createSequentialGroup()
                        .addComponent(txtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGrupo2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPresentacionLayout.createSequentialGroup()
                        .addComponent(txtIntegrantes, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIntegrantes3)
                            .addComponent(txtIntegrantes2)))
                    .addComponent(txtAsignatura1))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        panelPresentacionLayout.setVerticalGroup(
            panelPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPresentacionLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(imgUNI, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCarrera)
                .addGap(4, 4, 4)
                .addComponent(txtAsignatura1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAsignatura)
                .addGap(18, 18, 18)
                .addGroup(panelPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDocente)
                    .addComponent(txtDocente2))
                .addGap(18, 18, 18)
                .addGroup(panelPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGrupo)
                    .addComponent(txtGrupo2))
                .addGap(18, 18, 18)
                .addGroup(panelPresentacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIntegrantes)
                    .addComponent(txtIntegrantes2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIntegrantes3)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelPresentacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelPresentacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void imagen(JLabel imgUNI){
        ImageIcon uni = new ImageIcon("src/images/imgUNI,png");
        
        imgUNI.setIcon(uni);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgUNI;
    private javax.swing.JPanel panelPresentacion;
    private javax.swing.JLabel txtAsignatura;
    private javax.swing.JLabel txtAsignatura1;
    private javax.swing.JLabel txtCarrera;
    private javax.swing.JLabel txtDocente;
    private javax.swing.JLabel txtDocente2;
    private javax.swing.JLabel txtGrupo;
    private javax.swing.JLabel txtGrupo2;
    private javax.swing.JLabel txtIntegrantes;
    private javax.swing.JLabel txtIntegrantes2;
    private javax.swing.JLabel txtIntegrantes3;
    // End of variables declaration//GEN-END:variables
}
